### ISSUE TITLE
Error in project.xml

### ISSUE THREAD

**Issue by VishwasGagrani** [feathersui/webpack-openfl-loader#1]
I am trying to compile the basic example  but get this error

![Screen Shot 2022-11-28 at 6 25 16 PM](https://user-images.githubusercontent.com/294382/204283816-a0bf0042-8399-43f7-98bd-c36e65d01f93.png)

**Comment by joshtynjala** [comment]
> Error: Cannot find module 'node: child_process'

You might need to update Node.js to a newer version. According to [this page](https://nodejs.org/api/modules.html#core-modules), you need Node.js v14.18 or newer.

**Comment by VishwasGagrani** [comment]
I have 15.0
![Screen Shot 2022-11-28 at 11 09 34 PM](https://user-images.githubusercontent.com/294382/204344527-c1810646-d6e9-4240-85af-bb433b3f0088.png)

**Comment by joshtynjala** [comment]
Node.js 15 wasn't an LTS release, so maybe 14.18 is actually newer than that. Support for the `node:` prefix was also added in 16, so I recommend upgrading from 15 to 16.

**Comment by VishwasGagrani** [comment]
Thanks. It works now! 

I have older version of Mac El Capitan, so it does not support more than 15.10 
So, I tried it on windows with node version 18.0 

However I had to update the package.json as follows ( removing uglify as it was showing some dependency issue with webpack 5.0) :

{
  "name": "main",
  "version": "1.0.0",
  "private": true,
  "config": {
    "haxe": "3.4.4"
  },
  "devDependencies": {
    "haxe": "^5.2.1",
    "haxe-loader": "^0.10.0",
    "openfl": "^8.9.6",
    "webpack": "^5.75.0",
    "webpack-dev-server": "^4.11.1",
    "webpack-merge": "^5.8.0"
  },
  "scripts": {
    "build": "npm run build:prod",
    "build:dev": "webpack --config webpack.dev.js",
    "build:prod": "webpack --config webpack.prod.js",
    "start": "npm run start:dev",
    "start:dev": "webpack-dev-server --open --config webpack.dev.js",
    "start:prod": "webpack-dev-server --open --config webpack.prod.js"
  }
}

**Comment by joshtynjala** [comment]
The package.json that you posted isn't even using webpack-openfl-loader...

It also seems to be referencing the npm version of OpenFL. webpack-openfl-loader is designed to be used with the Haxelib version of OpenFL.

**Comment by VishwasGagrani** [comment]
Ok. I did not notice that.
The original package.json was showing some problem with the latest node version. So after some research I used this command:
 npm install -g npm-check-updates
 
 And it modified my package.json automatically. 
 
 
 I was getting these errors when trying to use the original package.json 
 
 npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: main@1.0.0
npm ERR! Found: webpack@5.75.0
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"^5.75.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.0.0" from uglifyjs-webpack-plugin@2.2.0
npm ERR! node_modules/uglifyjs-webpack-plugin
npm ERR!   dev uglifyjs-webpack-plugin@"^2.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:

**Comment by joshtynjala** [comment]
For reference, this is the package.json from the basic sample:

```json
{
  "name": "openfl-loader-basic-sample",
  "version": "1.0.0",
  "description": "A basic sample to demonstrate openfl-loader",
  "repository": "https://github.com/feathersui/webpack-openfl-loader.git",
  "devDependencies": {
    "webpack-cli": "^4.10.0",
    "webpack-dev-server": "^4.9.2",
    "openfl-loader": "^1.0.0"
  },
  "scripts": {
    "start": "webpack serve --mode=development",
    "build": "webpack --mode=production"
  }
}
```

Much simpler, as you can see!

**Comment by VishwasGagrani** [comment]
I downloaded everything again and tried it running from scratch without changing anything this time. 
I get this error

ERROR in ./project.xml 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <?xml version="1.0" encoding="utf-8"?>
| <project>
|

**Comment by joshtynjala** [comment]
It sounds like your webpack.config.js file doesn't contain the rule for project.xml to be handled by openfl-loader.

```js
rules: [
  {
    test: /\/project\.xml$/,
    use: [
      {
        loader: "openfl-loader",
      },
    ],
  },
],
```

Or maybe you forgot to install openfl-loader with npm?

This error doesn't make sense for the basic sample. If you're creating a new project instead of compiling the basic sample, then you should look for differences between your project and the basic sample.

**Comment by VishwasGagrani** [comment]
Hmm. I downloaded the files again from this  github repository. And did not change anything this time.
Just used npm install. ( That installed everything including openfl-loader. I can see the folder openfl-loader inside the node_modules.  )

And then npm start. 

Here is how it looks :
module.exports = {
  entry: "./project.xml",
  output: {
    filename: "basic.bundle.js",
  },
  module: {
    rules: [
      {
        test: /\/project\.xml$/,
        use: [
          {
            loader: "openfl-loader",
          },
        ],
      },
    ],
  },
};

Anyway, I think I will sort it out soon. Or will let you know if the error still persist. Thanks for your help.

**Comment by joshtynjala** [comment]
Yeah, `npm install` and `npm start` in _samples/basic_ should be all you need. I just tried it myself, and it works on my machine.

**Comment by joshtynjala** [comment]
Well, I should mention that it's not necessarily _all_ you need. You need to run the Haxe installer manually, and you should install OpenFL in a terminal with `haxelib` too.

**Comment by VishwasGagrani** [comment]
I see. 
 Overall my aim was looking for compiling openfl project ( targeting html5) using npm. 
 Rather than using "openfl test html5" on terminal.
 Npm has got many features like hot-reloading.
 
 I saw your repository. And also this one
https://github.com/openfl/openfl-samples-haxe/tree/master/demos/PiratePig
How is it different from yours? Which one should I use?

**Comment by joshtynjala** [comment]
> How is it different from yours?

The PiratePig sample that you linked to appears to be using Webpack with haxe-loader. I am not very familiar with haxe-loader. From what I can tell the project seems to bypass `openfl test html5` and doesn't have a _project.xml_ file. It seems to compile from a _.hxml_ file instead, which is more like non-OpenFL Haxe projects. I think that it is using the npm version of OpenFL, which is a separate release from the Haxelib version of OpenFL. You should know that the npm version of OpenFL hasn't been updated since before OpenFL 9, so it doesn't have the latest bug fixes and features.

openfl-loader more closely matches the _project.xml_ and `openfl test html5` way of doing things, while still allowing the resulting JS files to be processed by Webpack.

> Which one should I use?

Since I haven't used haxe-loader, I can't really say if it is better or not. For my needs, haxe-loader wouldn't be better. If you are used to the `openfl test html5` way of doing things, openfl-loader will be closer to that than haxe-loader, I think.

In both cases, it should be possible to have your project automatically recompile and reload the page when you make changes to _.hx_ source code. As I understand it, that's all provided by the Webpack dev server, regardless of which loader you use.
